name: Test With Pytest
on: push
jobs:
  test:
    name: Run pytest and scan with Sonar Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install Dependencies and Test
        env:
          GIFTBIT_API_KEY: ${{ secrets.GIFTBIT_API_KEY }}
          TEST_GIFT_ID: ${{ secrets.TEST_GIFT_ID }}
        run: |
          export PATH=/home/runner/.local/bin:$PATH
          pip install -r requirements_dev.txt
          PYTHONPATH=. pytest --cov-report xml --cov=pygiftbit tests/
          sed -i 's/\/home\/runner\/work\/pygiftbit\/pygiftbit\//\/github\/workspace\//g' coverage.xml
      - name: Scan with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Trigger Publish Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: donaldkbrown/pygiftbit
          event-type: pypi-publish
